<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_foto_rumah_model extends CI_Model
{

    public $table = 'tbl_foto_rumah';
    public $id = 'id_foto_rumah';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, 'ASC');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_foto_rumah', $q);
        $this->db->or_like('id_tipe', $q);
        $this->db->or_like('ukuran_awal', $q);
        $this->db->or_like('ukuran_akhir', $q);
        $this->db->or_like('foto', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_foto_rumah', $q);
        $this->db->or_like('id_tipe', $q);
        $this->db->or_like('ukuran_awal', $q);
        $this->db->or_like('ukuran_akhir', $q);
        $this->db->or_like('foto', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function delete_photo_rumah_by_url($id_foto_rumah, $photo_url) {
        // Fetch the existing photo URLs
        $foto = $this->db->select('foto')
                               ->where('id_foto_rumah', $id_foto_rumah)
                               ->get('tbl_foto_rumah')
                               ->row()
                               ->foto;

        // Explode the fetched photo string into an array of photo URLs
        $photos = array_map('trim', explode(",", $foto));

        // Find the index of the photo URL to delete
        $index = array_search($photo_url, $photos);

        if ($index !== false) {
            // Remove the photo URL from the array
            unset($photos[$index]);

            // Implode the array back into a comma-separated string
            $updated_foto = implode(",", $photos);

            // Update the database record with the updated foto
            $this->db->where('id_foto_rumah', $id_foto_rumah)
                     ->update('tbl_foto_rumah', ['foto' => $updated_foto]);

            // Return TRUE if update was successful
            return true;
        }

        // Return FALSE if photo URL was not found
        return false;
    }

}

/* End of file Tbl_foto_rumah_model.php */
/* Location: ./application/models/Tbl_foto_rumah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-07-26 05:57:15 */
/* http://harviacode.com */